from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]

REQUIRED_PATHS = [
    "AGENTS.md",
    "README.md",
    "WORKSPACE.md",
    "workspace-system-manifest.md",
    "workspace-records/README.md",
    "workspace-records/upgrades/ws-core-v0.3.0-adoption.md",
    "workspace-records/implementation/2026-07-03-ws-core-v0.3.0-fresh-workspace-landing.md",
    "workspace-records/decisions/2026-07-03-ws-core-v0.3.0-local-decisions.md",
    "workspace-records/checks/2026-07-03-ws-core-v0.3.0-verification.md",
    "workspace-records/feedback/README.md",
    "workspace-records/feedback/2026-07-03-ws-core-v0.3.0-core-feedback.md",
    "workspace-records/feedback/2026-07-03-ws-core-v0.3.0-feedback-interface.md",
    "workspace-records/feedback/sanitized-signal-template.md",
    "workspace-records/feedback/self-repair-record-template.md",
    "docs/workspaces/receiver-operating-standard.md",
    "docs/workspaces/entry-and-record-standard.md",
    "docs/workspaces/upgrade-playbook.md",
    "docs/releases/ws-core-v0.3.0-complete-beta-release.md",
    "docs/sync/starter-github-sync.md",
    "projects/starter/plan.md",
    "scripts/utils/check_sync.py",
    "scripts/utils/verify_open_box.py",
]

REQUIRED_SNIPPETS = {
    "WORKSPACE.md": [
        "WorkSeed Workspace Template",
        "workspace-template-v0.1.0",
        "ws-core-v0.3.0",
        "Generated by: `scripts/utils/create_workspace_deployment.py`",
        "Adoption state: `Applied` for template baseline creation",
    ],
    "workspace-system-manifest.md": [
        "Workspace system name: WorkSeed Workspace Template",
        "Workspace remote: `https://github.com/raymondhyg/workseed-workspace-template`",
        "Template version: `workspace-template-v0.1.0`",
        "Core tag: `ws-core-v0.3.0`",
        "Core commit: `a5b8b7355e02ef26e51d6af53b2bec28a14d08cb`",
        "Built-in feedback interface",
        "Prism | Not evaluated",
        "Mark | Not evaluated",
        "mira | Not evaluated",
        "Mock/read-only only",
    ],
    "docs/sync/starter-github-sync.md": [
        "https://github.com/raymondhyg/workseed-workspace-template",
        "Visibility: `public`",
        "python scripts/utils/check_workspace_deployment.py",
    ],
    "docs/releases/workspace-template-v0.1.0.md": [
        "WorkSeed Workspace Template v0.1.0",
        "Base Core release: `ws-core-v0.3.0`",
        "No customer facts.",
        "not Template v1.0",
    ],
    "workspace-records/feedback/2026-07-03-ws-core-v0.3.0-feedback-interface.md": [
        "Built-In Feedback Interface",
        "Workspace self-repair",
        "Core sanitized signal",
        "Blocked private",
    ],
    "workspace-records/feedback/README.md": [
        "Workspace Feedback Interface",
        "Self-repair locally",
        "sanitized Core signal",
    ],
    "workspace-records/feedback/sanitized-signal-template.md": [
        "Sanitized Core Signal Template",
        "Private Material Removed",
        "future `0.3.x` patch candidate",
    ],
    "workspace-records/feedback/self-repair-record-template.md": [
        "Workspace Self-Repair Record Template",
        "Core Signal Decision",
        "no Core signal needed",
    ],
}

FORBIDDEN_SNIPPETS = [
    "product-grade: yes",
    "source-equivalent: yes",
    "real adapter connected: yes",
    "external task written: yes",
]


def fail(message: str) -> None:
    print(f"[FAIL] {message}")
    raise SystemExit(1)


def main() -> int:
    for rel in REQUIRED_PATHS:
        if not (ROOT / rel).exists():
            fail(f"missing required path: {rel}")

    for rel, snippets in REQUIRED_SNIPPETS.items():
        text = (ROOT / rel).read_text(encoding="utf-8")
        for snippet in snippets:
            if snippet not in text:
                fail(f"{rel} missing text: {snippet}")

    for path in ROOT.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        if path == Path(__file__).resolve():
            continue
        if path.suffix.lower() not in {".md", ".py", ".txt", ".toml", ".json", ".yaml", ".yml"}:
            continue
        text = path.read_text(encoding="utf-8")
        for snippet in FORBIDDEN_SNIPPETS:
            if snippet in text:
                fail(f"{path.relative_to(ROOT)} contains forbidden claim: {snippet}")

    print("[PASS] Workspace deployment checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
