from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]

REQUIRED_PATHS = [
    "AGENTS.md",
    "README.md",
    "WORKSPACE.md",
    "workspace-system-manifest.md",
    "workspace-records/README.md",
    "workspace-records/upgrades/ws-core-v0.3.0-adoption.md",
    "workspace-records/implementation/2026-07-03-ws-core-v0.3.0-fresh-workspace-landing.md",
    "workspace-records/implementation/2026-07-03-template-initialization-core-loading.md",
    "workspace-records/decisions/2026-07-03-ws-core-v0.3.0-local-decisions.md",
    "workspace-records/checks/2026-07-03-ws-core-v0.3.0-verification.md",
    "workspace-records/feedback/README.md",
    "workspace-records/capability-loads/README.md",
    "workspace-records/feedback/2026-07-03-ws-core-v0.3.0-core-feedback.md",
    "workspace-records/feedback/2026-07-03-ws-core-v0.3.0-feedback-interface.md",
    "workspace-records/feedback/sanitized-signal-template.md",
    "workspace-records/feedback/self-repair-record-template.md",
    "docs/workspaces/receiver-operating-standard.md",
    "docs/workspaces/entry-and-record-standard.md",
    "docs/workspaces/upgrade-playbook.md",
    "docs/workspaces/initialization-and-core-loading.md",
    "docs/releases/ws-core-v0.3.0-complete-beta-release.md",
    "docs/sync/starter-github-sync.md",
    "projects/starter/plan.md",
    "scripts/utils/check_sync.py",
    "scripts/utils/verify_open_box.py",
    "scripts/utils/install_core_capabilities.py",
    "templates/first-workspace-initialization-prompt.md",
    "templates/core-capability-load-record-template.md",
]

REQUIRED_SNIPPETS = {
    "WORKSPACE.md": [
        "WorkSeed Workspace Template",
        "workspace-template-v0.1.0",
        "ws-core-v0.3.0",
        "Generated by: `scripts/utils/create_workspace_deployment.py`",
        "Adoption state: `Applied` for template baseline creation",
        "Core Capability Runtime Loading",
        "install_core_capabilities.py",
    ],
    "workspace-system-manifest.md": [
        "Workspace system name: WorkSeed Workspace Template",
        "Workspace remote: `https://github.com/raymondhyg/workseed-workspace-template`",
        "Template version: `workspace-template-v0.1.0`",
        "Core tag: `ws-core-v0.3.0`",
        "Core commit: `a5b8b7355e02ef26e51d6af53b2bec28a14d08cb`",
        "Built-in feedback interface",
        "Core capability runtime loading",
        "Prism | Not evaluated",
        "Mark | Not evaluated",
        "mira | Not evaluated",
        "Mock/read-only only",
    ],
    "docs/sync/starter-github-sync.md": [
        "https://github.com/raymondhyg/workseed-workspace-template",
        "Visibility: `public`",
        "python scripts/utils/check_workspace_deployment.py",
    ],
    "docs/releases/workspace-template-v0.1.0.md": [
        "WorkSeed Workspace Template v0.1.0",
        "基础 Core 版本：`ws-core-v0.3.0`",
        "不包含客户事实。",
        "不声称 Template v1.0。",
    ],
    "README.md": [
        "这是 WorkSeed 的公开 Workspace 模板仓库。",
        "Core 版本：`ws-core-v0.3.0`",
        "Template 版本：`workspace-template-v0.1.0`",
        "Use this template",
        "第一次打开时怎么初始化",
        "如何加载 Core 能力文件",
        "install_core_capabilities.py",
    ],
    "docs/workspaces/initialization-and-core-loading.md": [
        "Workspace Initialization And Core Loading",
        "First Greeting Prompt",
        "先用 2-3 句话介绍自己",
        "Loading From A Zip Package",
        "install_core_capabilities.py",
        ".codex/agents/*.toml",
        ".agents/skills/*/SKILL.md",
        "restart or reopen the Workspace in Codex",
    ],
    "templates/first-workspace-initialization-prompt.md": [
        "docs/workspaces/initialization-and-core-loading.md",
        "先用 2-3 句话介绍自己",
        "是否已经安装可运行 Core capability files",
        ".codex/agents",
        ".agents/skills",
    ],
    "templates/core-capability-load-record-template.md": [
        "Core Capability Load Record",
        "zip package",
        "Installed Runtime Surfaces",
    ],
    "workspace-records/capability-loads/README.md": [
        "Capability Loads",
        "local Core repo",
        "zip package",
        "install_core_capabilities.py",
    ],
    "workspace-records/implementation/2026-07-03-template-initialization-core-loading.md": [
        "Template Initialization And Core Loading Implementation",
        "first greeting to usable Workspace",
        "local Core repo",
        "zip package",
        "install_core_capabilities.py",
        "zip-package dry-run smoke",
    ],
    "workspace-records/feedback/2026-07-03-ws-core-v0.3.0-feedback-interface.md": [
        "Built-In Feedback Interface",
        "Workspace self-repair",
        "Core sanitized signal",
        "Blocked private",
    ],
    "workspace-records/feedback/README.md": [
        "Workspace Feedback Interface",
        "Self-repair locally",
        "sanitized Core signal",
    ],
    "workspace-records/feedback/sanitized-signal-template.md": [
        "Sanitized Core Signal Template",
        "Private Material Removed",
        "future `0.3.x` patch candidate",
    ],
    "workspace-records/feedback/self-repair-record-template.md": [
        "Workspace Self-Repair Record Template",
        "Core Signal Decision",
        "no Core signal needed",
    ],
}

FORBIDDEN_SNIPPETS = [
    "product-grade: yes",
    "source-equivalent: yes",
    "real adapter connected: yes",
    "external task written: yes",
]


def fail(message: str) -> None:
    print(f"[FAIL] {message}")
    raise SystemExit(1)


def main() -> int:
    for rel in REQUIRED_PATHS:
        if not (ROOT / rel).exists():
            fail(f"missing required path: {rel}")

    for rel, snippets in REQUIRED_SNIPPETS.items():
        text = (ROOT / rel).read_text(encoding="utf-8")
        for snippet in snippets:
            if snippet not in text:
                fail(f"{rel} missing text: {snippet}")

    for path in ROOT.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        if path == Path(__file__).resolve():
            continue
        if path.suffix.lower() not in {".md", ".py", ".txt", ".toml", ".json", ".yaml", ".yml"}:
            continue
        text = path.read_text(encoding="utf-8")
        for snippet in FORBIDDEN_SNIPPETS:
            if snippet in text:
                fail(f"{path.relative_to(ROOT)} contains forbidden claim: {snippet}")

    print("[PASS] Workspace deployment checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
