from __future__ import annotations

import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]

REQUIRED_PATHS = [
    ".gitignore",
    "AGENTS.md",
    "README.md",
    "WORKSPACE.md",
    "workspace-system-manifest.md",
    "workspace-records/README.md",
    "workspace-records/upgrades/ws-core-v0.3.0-adoption.md",
    "workspace-records/implementation/2026-07-03-ws-core-v0.3.0-fresh-workspace-landing.md",
    "workspace-records/implementation/2026-07-03-template-initialization-core-loading.md",
    "workspace-records/decisions/2026-07-03-ws-core-v0.3.0-local-decisions.md",
    "workspace-records/checks/2026-07-03-ws-core-v0.3.0-verification.md",
    "workspace-records/feedback/README.md",
    "workspace-records/capability-loads/README.md",
    "workspace-records/feedback/2026-07-03-ws-core-v0.3.0-core-feedback.md",
    "workspace-records/feedback/2026-07-03-ws-core-v0.3.0-feedback-interface.md",
    "workspace-records/feedback/sanitized-signal-template.md",
    "workspace-records/feedback/self-repair-record-template.md",
    "docs/workspaces/receiver-operating-standard.md",
    "docs/workspaces/entry-and-record-standard.md",
    "docs/workspaces/upgrade-playbook.md",
    "docs/workspaces/initialization-and-core-loading.md",
    "docs/workspaces/network-health-and-reconnect-guide.md",
    "docs/assets/douyin-youguangmanyan-1688.jpg",
    "docs/releases/ws-core-v0.3.0-complete-beta-release.md",
    "docs/sync/starter-github-sync.md",
    "projects/starter/plan.md",
    "scripts/utils/check_sync.py",
    "scripts/utils/verify_open_box.py",
    "scripts/utils/check_network_health.py",
    "scripts/utils/check_network_health_redaction.py",
    "scripts/utils/check_network_health_guidance_replay.py",
    "scripts/utils/check_workspace_template_v0_1_3_package_readiness.py",
    "scripts/utils/check_workspace_template_v0_1_3_release_preflight.py",
    "scripts/utils/check_workspace_template_v0_1_4_package_readiness.py",
    "scripts/utils/check_workspace_template_v0_1_4_release_preflight.py",
    "scripts/utils/install_core_capabilities.py",
    "templates/first-workspace-initialization-prompt.md",
    "templates/core-runtime-availability-verification-prompt.md",
    "templates/runtime-visibility-test-thread-prompt.md",
    "templates/network-health-guidance-thread-prompt.md",
    "templates/network-health-source-thread-handoff-template.md",
    "templates/codex-env-network-template.txt",
    "templates/core-capability-load-record-template.md",
    "workspace-records/checks/network-health-check-template.md",
    "workspace-records/feedback/network-health-core-feedback-template.md",
    "docs/releases/workspace-template-v0.1.1.md",
    "docs/releases/workspace-template-v0.1.2.md",
    "docs/releases/workspace-template-v0.1.3-candidate.md",
    "docs/releases/workspace-template-v0.1.4.md",
]

REQUIRED_SNIPPETS = {
    ".gitignore": [
        ".codex/.env",
    ],
    "WORKSPACE.md": [
        "Workspace name:",
        "Workspace owner:",
        "Workspace purpose:",
        "workspace-template-v0.1.4",
        "ws-core-v0.3.1",
        "Capability runtime state: `not installed by default`",
        "Runtime availability: `not verified`",
        "does not itself prove that",
        "Generated by: `scripts/utils/create_workspace_deployment.py`",
        "Adoption state:",
        "Core Capability Runtime Loading",
        "install_core_capabilities.py",
    ],
    "workspace-system-manifest.md": [
        "Workspace system name:",
        "Workspace owner:",
        "Workspace purpose:",
        "Workspace local path:",
        "Workspace remote:",
        "Template version: `workspace-template-v0.1.4`",
        "Core tag: `ws-core-v0.3.1`",
        "Core commit: `ac576bbf347ef756bfcbf6d8fb2ce03b10646dcc`",
        "Current Capability State",
        "Concrete Core runtime files",
        "Not installed by default",
        "Receiver ready, not capability-ready",
        "Built-in feedback interface",
        "Core capability runtime loading",
        "Prism | Not evaluated",
        "Mark | Not evaluated",
        "mira | Not evaluated",
        "capability-radar | Not evaluated",
        "Mock/read-only only",
    ],
    "docs/sync/starter-github-sync.md": [
        "https://github.com/raymondhyg/workseed-workspace-template",
        "Visibility: `public`",
        "python scripts/utils/check_workspace_deployment.py",
    ],
    "docs/releases/workspace-template-v0.1.0.md": [
        "WorkSeed Workspace Template v0.1.0",
        "## 中文发布摘要",
        "发布版本：`workspace-template-v0.1.0`",
        "发布类型：公开模板基线",
        "主要变化：",
        "采用边界：",
        "没有做：",
        "验证结果：",
        "隐私边界：",
        "基础 Core 版本：`ws-core-v0.3.0`",
        "不包含客户事实。",
        "不声称 Template v1.0。",
    ],
    "docs/releases/workspace-template-v0.1.1.md": [
        "WorkSeed Workspace Template v0.1.1",
        "Core capability loading / runtime verification hardening candidate",
        "019f2b51-55b0-7c50-af67-b622c443709d",
        "runtime availability: `runtime verified`",
        "No Template tag was created.",
    ],
    "docs/releases/workspace-template-v0.1.2.md": [
        "WorkSeed Workspace Template v0.1.2",
        "## 中文发布摘要",
        "发布版本：`workspace-template-v0.1.2`",
        "发布类型：模板补丁发布",
        "主要变化：",
        "采用边界：",
        "没有做：",
        "验证结果：",
        "隐私边界：",
        "Status: published",
        "运行时可见性验证流程",
        "Git tag: `workspace-template-v0.1.2`",
        "GitHub Release: `https://github.com/raymondhyg/workseed-workspace-template/releases/tag/workspace-template-v0.1.2`",
        "019f2b63-310b-7640-af0c-77670017b5c4",
        "019f2b70-8f29-7c61-b9d5-af3d896a1cb1",
        "源控制线程",
        "state drift",
        "archive the test thread",
        "This publication creates the `workspace-template-v0.1.2` Template tag",
    ],
    "docs/releases/workspace-template-v0.1.3-candidate.md": [
        "WorkSeed Workspace Template v0.1.3 Candidate",
        "## 中文发布摘要",
        "发布版本：`workspace-template-v0.1.3` candidate",
        "当前状态：本地候选已落地，尚未 tag、尚未 GitHub Release、尚未发布。",
        "网络健康与重连恢复开箱指引",
        "templates/network-health-guidance-thread-prompt.md",
        "templates/network-health-source-thread-handoff-template.md",
        "templates/codex-env-network-template.txt",
        "scripts/utils/check_network_health.py",
        "scripts/utils/check_network_health_guidance_replay.py",
        "scripts/utils/check_workspace_template_v0_1_3_package_readiness.py",
        "scripts/utils/check_workspace_template_v0_1_3_release_preflight.py",
        "workspace-records/checks/network-health-check-template.md",
        ".codex/.env",
        "允许本地修复但禁止真实本地 env 被 Git 跟踪",
        "没有发布 `workspace-template-v0.1.3`",
        "does not claim publication",
    ],
    "docs/releases/workspace-template-v0.1.4.md": [
        "WorkSeed Workspace Template v0.1.4",
        "发布版本：`workspace-template-v0.1.4`",
        "关联 Core：`ws-core-v0.3.1`",
        "capability-radar",
        "missing: none",
        "skipped: none",
        "python scripts/utils/install_core_capabilities.py",
        "python scripts/utils/check_workspace_deployment.py",
        "python scripts/utils/verify_open_box.py",
    ],
    "docs/releases/ws-core-v0.3.0-complete-beta-release.md": [
        "WorkSeed Core Release Note",
        "## 中文发布摘要",
        "发布版本：`ws-core-v0.3.0`",
        "发布类型：MINOR",
        "主要变化：",
        "采用边界：",
        "没有做：",
        "验证结果：",
        "隐私边界：",
    ],
    "README.md": [
        "这是 WorkSeed 的公开 Workspace 模板仓库。",
        "Core 版本：`ws-core-v0.3.1`",
        "Template 版本：`workspace-template-v0.1.4`",
        "当前能力状态：已知道 Core 基线；默认未安装可运行能力文件",
        "Template 知道 Core 0.3，但 Template 本身不等于已经具备 Core 0.3",
        "确认安装",
        "不等于授权立即写入安装",
        "不要自动扫描",
        "Core 压缩包在哪里",
        "18002997691",
        "289566513",
        "douyin-youguangmanyan-1688.jpg",
        "Use this template",
        "第一次打开时怎么初始化",
        "给我指引一下",
        "如何加载 Core 能力文件",
        "install_core_capabilities.py",
        "core-runtime-availability-verification-prompt.md",
        "runtime-visibility-test-thread-prompt.md",
        "源线程必须读取测试线程报告",
        "Codex 运行时",
        "网络健康指南线程",
        "network-health-source-thread-handoff-template.md",
        "templates/network-health-guidance-thread-prompt.md",
        "templates/codex-env-network-template.txt",
        ".codex/.env",
    ],
    "docs/workspaces/initialization-and-core-loading.md": [
        "Workspace Initialization And Core Loading",
        "First Greeting Prompt",
        "帮我初始化",
        "给我指引一下",
        "Natural language triggers start guidance only",
        "do not authorize the receiving AI to auto-scan",
        "Core zip package",
        "18002997691",
        "289566513",
        "docs/assets/douyin-youguangmanyan-1688.jpg",
        "Confirmation Gate",
        "确认安装",
        "ask the user for the Core zip location",
        "先用 2-3 句话介绍自己",
        "Loading From A Zip Package",
        "How To Get The Core Zip Package",
        "State writeback",
        "update `workspace-system-manifest.md`",
        "Not installed by default",
        "install_core_capabilities.py",
        ".codex/agents/*.toml",
        ".agents/skills/*/SKILL.md",
        "restart or reopen the Workspace in Codex",
        "core-runtime-availability-verification-prompt.md",
        "Runtime availability",
        "generated Workspace itself",
        "runtime-visibility-test-thread-prompt.md",
        "The source thread owns the final truth",
        "archive the test thread",
        "Network Health Before Project Work",
        "network-health-guidance-thread-prompt.md",
        "network-health-source-thread-handoff-template.md",
        "codex-env-network-template.txt",
        "check_network_health.py",
        "network-health-check-template.md",
        ".codex/.env",
    ],
    "templates/first-workspace-initialization-prompt.md": [
        "docs/workspaces/initialization-and-core-loading.md",
        "Natural Triggers",
        "帮我初始化这个 Workspace",
        "安装 Core 能力",
        "给我指引一下",
        "These triggers start guidance. They are not permission to run a write install.",
        "不要自动扫描我的电脑",
        "Core 压缩包在哪里",
        "18002997691",
        "289566513",
        "确认安装",
        "不等于授权立即写入文件",
        "是否已经安装可运行 Core capability files",
        ".codex/agents",
        ".agents/skills",
        "core-runtime-availability-verification-prompt.md",
        "runtime-visibility-test-thread-prompt.md",
        "network-health-guidance-thread-prompt.md",
        "codex-env-network-template.txt",
        "check_network_health.py",
        ".codex/.env",
    ],
    "docs/workspaces/network-health-and-reconnect-guide.md": [
        "Network Health And Reconnect Guide",
        "repeated reconnects",
        "网络重连",
        "network health guidance thread",
        ".codex/.env",
        "templates/codex-env-network-template.txt",
        "templates/network-health-guidance-thread-prompt.md",
        "templates/network-health-source-thread-handoff-template.md",
        "Do not commit a real `.codex/.env` file",
        "python scripts/utils/check_network_health.py",
        "workspace-records/checks/network-health-check-template.md",
        "workspace-records/feedback/network-health-core-feedback-template.md",
        "port or proxy",
        "restart or reopen Codex",
        "workspace-records/checks/",
    ],
    "templates/network-health-guidance-thread-prompt.md": [
        "Network Health Guidance Thread Prompt",
        "Only diagnose network health and reconnect stability",
        "docs/workspaces/network-health-and-reconnect-guide.md",
        "templates/codex-env-network-template.txt",
        "workspace-records/checks/network-health-check-template.md",
        "workspace-records/feedback/network-health-core-feedback-template.md",
        "python scripts/utils/check_network_health.py",
        ".codex/.env",
        "key names only",
        "values redacted",
        "restart or reopen Codex",
        "no secrets exposed",
    ],
    "templates/network-health-source-thread-handoff-template.md": [
        "Network Health Source Thread Handoff Template",
        "source/control thread",
        "Workspace root:",
        "Observed symptom:",
        "Workspace-local `.codex/.env` port/proxy control",
        "python scripts/utils/check_network_health.py",
        "Do not commit a real `.codex/.env`",
        "Return to the source thread with:",
        "stability result: fixed / improved / not fixed / blocked / not verified",
        "workspace-records/feedback/network-health-core-feedback-template.md",
    ],
    "templates/codex-env-network-template.txt": [
        "Copy this file to:",
        ".codex/.env",
        "Do not commit .codex/.env",
        "CODEX_PORT=",
        "CODEX_API_PORT=",
        "CODEX_BROWSER_PORT=",
        "HTTP_PROXY=",
        "HTTPS_PROXY=",
        "NO_PROXY=localhost,127.0.0.1",
    ],
    "scripts/utils/check_network_health.py": [
        "NETWORK_KEYS",
        "CODEX_PORT",
        "values_redacted",
        "No env values printed.",
        "workspace-records/checks/network-health-check-template.md",
        "--env-path",
    ],
    "scripts/utils/check_network_health_redaction.py": [
        "Network health redaction passed",
        "local-redaction-probe.invalid",
        "SHOULD_NOT_PRINT",
        "values_redacted",
    ],
    "scripts/utils/check_network_health_guidance_replay.py": [
        "Resolution Loop",
        "Network health guidance replay passed",
        "not fixed",
        "blocked",
    ],
    "scripts/utils/check_workspace_template_v0_1_3_package_readiness.py": [
        "Workspace Template v0.1.3 package readiness passed",
        "PACKAGE_REQUIRED_PATHS",
        "FORBIDDEN_TRACKED_PATHS",
        ".codex/.env",
    ],
    "scripts/utils/check_workspace_template_v0_1_3_release_preflight.py": [
        "Workspace Template v0.1.3 release preflight passed",
        "RELEASE_REQUIRED_TRACKED_PATHS",
        "exist in HEAD before tag/archive",
        "no uncommitted changes",
        ".codex/.env",
    ],
    "scripts/utils/check_workspace_template_v0_1_4_package_readiness.py": [
        "Workspace Template v0.1.4 package readiness passed",
        "PACKAGE_REQUIRED_PATHS",
        "capability-radar",
        ".codex/.env",
    ],
    "scripts/utils/check_workspace_template_v0_1_4_release_preflight.py": [
        "Workspace Template v0.1.4 release preflight passed",
        "RELEASE_REQUIRED_TRACKED_PATHS",
        "exist in HEAD before tag/archive",
        "no uncommitted changes",
        ".codex/.env",
    ],
    "workspace-records/checks/network-health-check-template.md": [
        "Network Health Check Record",
        "reconnect count",
        ".codex/.env",
        "values redacted: yes",
        "python scripts/utils/check_network_health.py",
        "Resolution Loop",
        "final state: fixed / improved / not fixed / blocked / not verified",
        "no real `.codex/.env` committed",
        "Core feedback needed",
        "workspace-records/feedback/network-health-core-feedback-template.md",
    ],
    "workspace-records/feedback/network-health-core-feedback-template.md": [
        "Network Health Core Feedback Template",
        "not fixed",
        "blocked",
        "recognized key names only",
        "values redacted: yes",
        "no env values included",
        "no port/proxy values included",
        "Requested Core Decision",
    ],
    "templates/core-runtime-availability-verification-prompt.md": [
        "Core Runtime Availability Verification Prompt",
        "Natural Triggers",
        "帮我检查 Core 能不能用了",
        "Core 安装完了，下一步呢",
        "workspace-records/capability-loads",
        ".codex/agents",
        ".agents/skills",
        "workspace-system-manifest.md",
        "状态",
        "Not installed by default",
        "Runtime availability",
        "not verified",
        "不要把文件存在或本地检查 PASS 当成运行时可见",
        "确实运行在这个 Workspace 根目录",
        "runtime-visibility-test-thread-prompt.md",
        "archive the test thread",
    ],
    "templates/runtime-visibility-test-thread-prompt.md": [
        "Runtime Visibility Test Thread Prompt",
        "Source Thread Rule",
        "Only verify runtime visibility",
        "Do not edit files",
        "source thread must read this test result",
        "archive this test thread",
        "prism, mira, and Mark",
    ],
    "templates/core-capability-load-record-template.md": [
        "Core Capability Load Record",
        "zip package",
        "No auto-scan / no silent Core path reuse",
        "Installed Runtime Surfaces",
        "Missing Runtime Surfaces",
        "Skipped Extra Runtime Surfaces",
        "Runtime availability",
    ],
    "workspace-records/capability-loads/README.md": [
        "Capability Loads",
        "user-provided Core zip package",
        "do not auto-scan",
        "18002997691",
        "289566513",
        "zip package",
        "install_core_capabilities.py",
        "core-runtime-availability-verification-prompt.md",
        "runtime-visibility-test-thread-prompt.md",
    ],
    "workspace-records/implementation/2026-07-03-template-initialization-core-loading.md": [
        "Template Initialization And Core Loading Implementation",
        "first greeting to usable Workspace",
        "Core zip package",
        "auto-scanning",
        "18002997691",
        "289566513",
        "zip package",
        "install_core_capabilities.py",
        "zip-package dry-run smoke",
    ],
    "workspace-records/feedback/2026-07-03-ws-core-v0.3.0-feedback-interface.md": [
        "Built-In Feedback Interface",
        "Workspace self-repair",
        "Core sanitized signal",
        "Blocked private",
    ],
    "workspace-records/feedback/README.md": [
        "Workspace Feedback Interface",
        "Self-repair locally",
        "sanitized Core signal",
    ],
    "workspace-records/feedback/sanitized-signal-template.md": [
        "Sanitized Core Signal Template",
        "Private Material Removed",
        "future `0.3.x` patch candidate",
    ],
    "workspace-records/feedback/self-repair-record-template.md": [
        "Workspace Self-Repair Record Template",
        "Core Signal Decision",
        "no Core signal needed",
    ],
}

FORBIDDEN_SNIPPETS = [
    "product-grade: yes",
    "source-equivalent: yes",
    "real adapter connected: yes",
    "external task written: yes",
]


CHINESE_FIRST_RELEASE_NOTES = [
    "docs/releases/workspace-template-v0.1.0.md",
    "docs/releases/workspace-template-v0.1.2.md",
    "docs/releases/ws-core-v0.3.0-complete-beta-release.md",
]

CHINESE_TECHNICAL_RELEASE_SECTIONS = [
    "## 中文发布摘要",
    "## 技术变化",
    "## 受影响范围",
    "## 使用或采用方式",
    "## 验证证据",
    "## 明确没有做",
    "## 隐私和边界",
]


def fail(message: str) -> None:
    print(f"[FAIL] {message}")
    raise SystemExit(1)


def is_git_tracked(rel: str) -> bool:
    result = subprocess.run(
        ["git", "ls-files", "--error-unmatch", rel],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    return result.returncode == 0


def has_chinese_summary_immediately_after_title(text: str) -> bool:
    lines = text.splitlines()
    if not lines or not lines[0].startswith("# "):
        return False
    for line in lines[1:]:
        if not line.strip():
            continue
        return line.strip() == "## 中文发布摘要"
    return False


def main() -> int:
    if is_git_tracked(".codex/.env"):
        fail(".codex/.env must stay local and untracked")

    for rel in REQUIRED_PATHS:
        if not (ROOT / rel).exists():
            fail(f"missing required path: {rel}")

    for rel, snippets in REQUIRED_SNIPPETS.items():
        text = (ROOT / rel).read_text(encoding="utf-8")
        for snippet in snippets:
            if snippet not in text:
                fail(f"{rel} missing text: {snippet}")

    for rel in CHINESE_FIRST_RELEASE_NOTES:
        text = (ROOT / rel).read_text(encoding="utf-8")
        if not has_chinese_summary_immediately_after_title(text):
            fail(f"{rel} must place Chinese summary immediately after title")

    for rel in [
        "docs/releases/workspace-template-v0.1.0.md",
        "docs/releases/workspace-template-v0.1.2.md",
    ]:
        text = (ROOT / rel).read_text(encoding="utf-8")
        for section in CHINESE_TECHNICAL_RELEASE_SECTIONS:
            if section not in text:
                fail(f"{rel} missing Chinese technical release section: {section}")

    load_records = sorted((ROOT / "workspace-records" / "capability-loads").glob("*-capability-load.md"))
    for record in load_records:
        text = record.read_text(encoding="utf-8")
        for snippet in [
            "## Installed Runtime Surfaces",
            "## Missing Runtime Surfaces",
            "## Skipped Extra Runtime Surfaces",
            "## Runtime Availability",
            "Runtime availability: `",
        ]:
            if snippet not in text:
                fail(f"{record.relative_to(ROOT)} missing post-install field: {snippet}")

        required_installed = [
            ".codex/agents/capability-radar.toml",
            ".codex/agents/mark.toml",
            ".codex/agents/mira.toml",
            ".codex/agents/prism.toml",
            ".codex/agents/system-maintainer.toml",
            ".codex/agents/workflow-coach.toml",
            ".agents/skills/b2b-strategy/SKILL.md",
            ".agents/skills/background-memory/SKILL.md",
            ".agents/skills/capability-radar/SKILL.md",
            ".agents/skills/ecommerce-domain/SKILL.md",
            ".agents/skills/image-production/SKILL.md",
            ".agents/skills/prism-writeback/SKILL.md",
            ".agents/skills/reference-learning/SKILL.md",
            ".agents/skills/workflow-coach/SKILL.md",
            "docs/codex/prism-knowledge-writeback.md",
            "docs/capability-packs/b2b-strategy.md",
            "docs/capability-packs/image-production.md",
            "docs/core/p1/core-p1-prism-writeback-operating-loop-2026-07-03.md",
            "templates/prism-decision-template.md",
            "templates/mark-mira-prism-handoff-template.md",
        ]
        for rel in required_installed:
            if not (ROOT / rel).exists():
                fail(f"post-install record exists but required runtime surface is missing: {rel}")

    for path in ROOT.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        if path == Path(__file__).resolve():
            continue
        if path.suffix.lower() not in {".md", ".py", ".txt", ".toml", ".json", ".yaml", ".yml"}:
            continue
        text = path.read_text(encoding="utf-8")
        for snippet in FORBIDDEN_SNIPPETS:
            if snippet in text:
                fail(f"{path.relative_to(ROOT)} contains forbidden claim: {snippet}")

    print("[PASS] Workspace deployment checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
